WITH RECURSIVE GEN_DATA AS (
    -- 1. 1세대 (부모가 없는 최초의 대장균)
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 2. 자식 세대 계산 (부모 ID와 조인하여 세대를 1씩 증가)
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN_DATA G ON E.PARENT_ID = G.ID
)
-- 3. 자식이 없는 개체만 골라내어 세대별로 카운트
SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN_DATA A
WHERE NOT EXISTS (
    SELECT 1 
    FROM ECOLI_DATA B 
    WHERE B.PARENT_ID = A.ID
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;