SELECT 
    COUNT(*) AS FISH_COUNT, 
    MAX(LENGTH) AS MAX_LENGTH, 
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33  -- 👈 NULL을 10으로 취급해서 평균 계산!
ORDER BY FISH_TYPE ASC;